version: '3.8'

services:
  ws-postgres-db:
    image: postgres:15
    container_name: ws-postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: whale_sentinel_db
      POSTGRES_USER: whale_sentinel_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravelnet

volumes:
  pgdata:

networks:
  laravelnet:
